package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 28, 2017 6:19:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Creditcard generated by hbm2java
 */
public class Creditcard  implements java.io.Serializable {


     private long number;
     private String expireDate;
     private Double balance;
     private Set<User> users = new HashSet(0);

    public Creditcard() {
    }

	
    public Creditcard(long number) {
        this.number = number;
    }
    public Creditcard(long number, String expireDate, Double balance, Set users) {
       this.number = number;
       this.expireDate = expireDate;
       this.balance = balance;
       this.users = users;
    }
   
    public long getNumber() {
        return this.number;
    }
    
    public void setNumber(long number) {
        this.number = number;
    }
    public String getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


