package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 28, 2017 6:19:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Date date;
     private Integer status;
     private Set orderdetailses = new HashSet(0);

    public Orders() {
    }

	
    public Orders(User user) {
        this.user = user;
    }
    public Orders(User user, Date date, Integer status, Set orderdetailses) {
       this.user = user;
       this.date = date;
       this.status = status;
       this.orderdetailses = orderdetailses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set orderdetailses) {
        this.orderdetailses = orderdetailses;
    }




}


