package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 28, 2017 6:19:27 PM by Hibernate Tools 4.3.1



/**
 * Orderdetails generated by hbm2java
 */
public class Orderdetails  implements java.io.Serializable {


     private Integer id;
     private Orders orders;
     private Products products;
     private double price;
     private int quantity;

    public Orderdetails() {
    }

    public Orderdetails(Orders orders, Products products, double price, int quantity) {
       this.orders = orders;
       this.products = products;
       this.price = price;
       this.quantity = quantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


