package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 27, 2017 8:07:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductreviewsId generated by hbm2java
 */
@Embeddable
public class ProductreviewsId  implements java.io.Serializable {


     private int id;
     private String userEmail;
     private int productsProductId;

    public ProductreviewsId() {
    }

    public ProductreviewsId(int id, String userEmail, int productsProductId) {
       this.id = id;
       this.userEmail = userEmail;
       this.productsProductId = productsProductId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="User_email", nullable=false, length=45)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }


    @Column(name="products_product_id", nullable=false)
    public int getProductsProductId() {
        return this.productsProductId;
    }
    
    public void setProductsProductId(int productsProductId) {
        this.productsProductId = productsProductId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductreviewsId) ) return false;
		 ProductreviewsId castOther = ( ProductreviewsId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getUserEmail()==castOther.getUserEmail()) || ( this.getUserEmail()!=null && castOther.getUserEmail()!=null && this.getUserEmail().equals(castOther.getUserEmail()) ) )
 && (this.getProductsProductId()==castOther.getProductsProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getUserEmail() == null ? 0 : this.getUserEmail().hashCode() );
         result = 37 * result + this.getProductsProductId();
         return result;
   }   


}


