package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 27, 2017 8:07:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="onlineshopping"
    , uniqueConstraints = @UniqueConstraint(columnNames="productName") 
)
public class Products  implements java.io.Serializable {


     private Integer productId;
     private String productName;
     private double price;
     private int quantity;
     private String imageUrl;
     private String description;
     private Double discount;
     private String categoryName;
     private Set productreviewses = new HashSet(0);
     private Set productimageses = new HashSet(0);
     private Set orderdetailses = new HashSet(0);

    public Products() {
    }

	
    public Products(String productName, double price, int quantity, String imageUrl, String description, String categoryName) {
        this.productName = productName;
        this.price = price;
        this.quantity = quantity;
        this.imageUrl = imageUrl;
        this.description = description;
        this.categoryName = categoryName;
    }
    public Products(String productName, double price, int quantity, String imageUrl, String description, Double discount, String categoryName, Set productreviewses, Set productimageses, Set orderdetailses) {
       this.productName = productName;
       this.price = price;
       this.quantity = quantity;
       this.imageUrl = imageUrl;
       this.description = description;
       this.discount = discount;
       this.categoryName = categoryName;
       this.productreviewses = productreviewses;
       this.productimageses = productimageses;
       this.orderdetailses = orderdetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    
    @Column(name="productName", unique=true, nullable=false, length=45)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="imageUrl", nullable=false, length=1024)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="description", nullable=false, length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="discount", precision=22, scale=0)
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    
    @Column(name="categoryName", nullable=false, length=45)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set getProductreviewses() {
        return this.productreviewses;
    }
    
    public void setProductreviewses(Set productreviewses) {
        this.productreviewses = productreviewses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set getProductimageses() {
        return this.productimageses;
    }
    
    public void setProductimageses(Set productimageses) {
        this.productimageses = productimageses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set orderdetailses) {
        this.orderdetailses = orderdetailses;
    }




}


