package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 27, 2017 8:07:42 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productreviews generated by hbm2java
 */
@Entity
@Table(name="productreviews"
    ,catalog="onlineshopping"
)
public class Productreviews  implements java.io.Serializable {


     private ProductreviewsId id;
     private Products products;
     private User user;
     private String comment;

    public Productreviews() {
    }

	
    public Productreviews(ProductreviewsId id, Products products, User user) {
        this.id = id;
        this.products = products;
        this.user = user;
    }
    public Productreviews(ProductreviewsId id, Products products, User user, String comment) {
       this.id = id;
       this.products = products;
       this.user = user;
       this.comment = comment;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="userEmail", column=@Column(name="User_email", nullable=false, length=45) ), 
        @AttributeOverride(name="productsProductId", column=@Column(name="products_product_id", nullable=false) ) } )
    public ProductreviewsId getId() {
        return this.id;
    }
    
    public void setId(ProductreviewsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="products_product_id", nullable=false, insertable=false, updatable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_email", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="comment")
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


