package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 28, 2017 6:19:27 PM by Hibernate Tools 4.3.1



/**
 * Productreviews generated by hbm2java
 */
public class Productreviews  implements java.io.Serializable {


     private ProductreviewsId id;
     private Products products;
     private User user;
     private String comment;

    public Productreviews() {
    }

	
    public Productreviews(ProductreviewsId id, Products products, User user) {
        this.id = id;
        this.products = products;
        this.user = user;
    }
    public Productreviews(ProductreviewsId id, Products products, User user, String comment) {
       this.id = id;
       this.products = products;
       this.user = user;
       this.comment = comment;
    }
   
    public ProductreviewsId getId() {
        return this.id;
    }
    
    public void setId(ProductreviewsId id) {
        this.id = id;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


