package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 28, 2017 6:19:27 PM by Hibernate Tools 4.3.1



/**
 * Productimages generated by hbm2java
 */
public class Productimages  implements java.io.Serializable {


     private ProductimagesId id;
     private Products products;

    public Productimages() {
    }

    public Productimages(ProductimagesId id, Products products) {
       this.id = id;
       this.products = products;
    }
   
    public ProductimagesId getId() {
        return this.id;
    }
    
    public void setId(ProductimagesId id) {
        this.id = id;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }




}


