package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 27, 2017 8:07:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rechargecards generated by hbm2java
 */
@Entity
@Table(name="rechargecards"
    ,catalog="onlineshopping"
)
public class Rechargecards  implements java.io.Serializable {


     private int number;
     private Integer value;
     private String status;

    public Rechargecards() {
    }

	
    public Rechargecards(int number) {
        this.number = number;
    }
    public Rechargecards(int number, Integer value, String status) {
       this.number = number;
       this.value = value;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="number", unique=true, nullable=false)
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }

    
    @Column(name="value")
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }

    
    @Column(name="status", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


