package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 28, 2017 6:19:27 PM by Hibernate Tools 4.3.1



/**
 * Rechargecards generated by hbm2java
 */
public class Rechargecards  implements java.io.Serializable {


     private int number;
     private Integer value;
     private String status;

    public Rechargecards() {
    }

	
    public Rechargecards(int number) {
        this.number = number;
    }
    public Rechargecards(int number, Integer value, String status) {
       this.number = number;
       this.value = value;
       this.status = status;
    }
   
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


