package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 27, 2017 8:07:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="onlineshopping"
)
public class User  implements java.io.Serializable {


     private String email;
     private Creditcard creditcard;
     private String gender;
     private String firstName;
     private String lastName;
     private Date birthDate;
     private String password;
     private String phone;
     private String imageurl;
     private String type;
     private String address;
     private Set productreviewses = new HashSet(0);
     private Set orderses = new HashSet(0);

    public User() {
    }

	
    public User(String email, String gender, String firstName, String lastName, String password, String type) {
        this.email = email;
        this.gender = gender;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.type = type;
    }
    public User(String email, Creditcard creditcard, String gender, String firstName, String lastName, Date birthDate, String password, String phone, String imageurl, String type, String address, Set productreviewses, Set orderses) {
       this.email = email;
       this.creditcard = creditcard;
       this.gender = gender;
       this.firstName = firstName;
       this.lastName = lastName;
       this.birthDate = birthDate;
       this.password = password;
       this.phone = phone;
       this.imageurl = imageurl;
       this.type = type;
       this.address = address;
       this.productreviewses = productreviewses;
       this.orderses = orderses;
    }
   
     @Id 

    
    @Column(name="email", unique=true, nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creditCard_number")
    public Creditcard getCreditcard() {
        return this.creditcard;
    }
    
    public void setCreditcard(Creditcard creditcard) {
        this.creditcard = creditcard;
    }

    
    @Column(name="gender", nullable=false, length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="firstName", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastName", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthDate", length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="imageurl", length=1024)
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    
    @Column(name="type", nullable=false, length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getProductreviewses() {
        return this.productreviewses;
    }
    
    public void setProductreviewses(Set productreviewses) {
        this.productreviewses = productreviewses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


