package com.onlineshop.hibernatemodel.pojo;
// Generated Apr 28, 2017 6:19:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String email;
     private Creditcard creditcard;
     private String gender;
     private String firstName;
     private String lastName;
     private Date birthDate;
     private String password;
     private String phone;
     private String imageurl;
     private String type;
     private String address;
     private Set productreviewses = new HashSet(0);
     private Set orderses = new HashSet(0);

    public User() {
    }

	
    public User(String email, String gender, String firstName, String lastName, String password, String type) {
        this.email = email;
        this.gender = gender;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.type = type;
    }
    public User(String email, Creditcard creditcard, String gender, String firstName, String lastName, Date birthDate, String password, String phone, String imageurl, String type, String address, Set productreviewses, Set orderses) {
       this.email = email;
       this.creditcard = creditcard;
       this.gender = gender;
       this.firstName = firstName;
       this.lastName = lastName;
       this.birthDate = birthDate;
       this.password = password;
       this.phone = phone;
       this.imageurl = imageurl;
       this.type = type;
       this.address = address;
       this.productreviewses = productreviewses;
       this.orderses = orderses;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Creditcard getCreditcard() {
        return this.creditcard;
    }
    
    public void setCreditcard(Creditcard creditcard) {
        this.creditcard = creditcard;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getProductreviewses() {
        return this.productreviewses;
    }
    
    public void setProductreviewses(Set productreviewses) {
        this.productreviewses = productreviewses;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


